---
# tasks file for cdg.packstack
- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  notify:
    - Reboot

- name: Install OpenStack
  ansible.builtin.dnf:
    name:  "{{package.name  | default('') }}"
    state: "{{package.state | default('present') }}"
  loop: "{{ packstack_packages | default([])}}"
  loop_control:
    loop_var: "package"

- name: OpenStack Config File
  ansible.builtin.template:
    src:   "{{ packstack_answers.src   | default('answers.j2') }}"
    dest:  "{{ packstack_answers.dest  | default('/tmp/answers.txt') }}" 
    owner: "{{ packstack_answers.owner | default('root') }}" 
    group: "{{ packstack_answers.group | default('wheel') }}" 
    mode:  "{{ packstack_answers.mode  | default('u=rw,g=r,o=r') }}"  

- name: OpenStack Installation
  command:
    cmd: "nohup packstack --answer-file {{ packstack_answers.dest  | default('/tmp/answers.txt') }} &"
