- name: "Wait for port 80 to become open on |{{packstack_default_host_ip| default(omit)}}|, don't start checking for 10 seconds"
  ansible.builtin.wait_for:
    host: "{{packstack_default_host_ip| default(omit)}}"
    port: 80
    delay: 10

- name: "Test Installation |{{openstack_dashboard|default('')}}|"
  ansible.builtin.uri:
    url: "{{openstack_dashboard|default('')}}"
    method: "POST"
    body_format: "form-urlencoded"
    body:
    - [ name, 'admin' ]
    - [ password, "{{packstack_options.defaults.password|default('')}}" ]
    - [ enter, 'Sign in' ]
    status_code: "302"
  register: "_login"
  until: "_login.status == 302"
