# ---> Hostname
- name: Set a hostname |{{server_hostname| default('host')}}|
  hostname:
     name: "{{server_hostname| default('host')}}"

# ---> Services
- name: 'Enable/Disable Server Services'
  ignore_errors: yes
  service:
    name:   "{{ server_service.name }}"
    state:  "{{ server_service.state | default('stopped') }}" 
    enabled: "{{ server_service.state | bool }}" 
  loop: "{{ server_services | default([]) }}"
  loop_control:
    loop_var: "server_service"
  when: 
    - "server_services is defined"
    - "server_services is not none"
    - "server_services is not string"
    - "server_services is not mapping"
    - "server_service.name is defined"
    - "server_service.name is not none"
    - "server_service.name is string"  

