---
# --- Prepare
- hosts: "openstack" 
  become: "true"
  tasks:
    - name: "Prepare Server" 
      include_tasks: "prepare.yml"

# --- Provision
- hosts: "openstack" 
  become: "true"
  roles:
    #- role: fedora.linux_system_roles.selinux
    #- role: fedora.linux_system_roles.storage
    - role: cdg.openstack
