---
# -- Server Properties
server_hostname: openstack-test
server_repositories:
  - name: https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/centos-stream-repos-9.0-28.el9.noarch.rpm  
    state: present
  - name: 
      - epel-release 
      - epel-next-release  
    state: present
    
server_dnf_config_manager:
  - name: 
     - crb
    state: enabled
    
server_services:
  - name: "firewalld"
    enabled: no 
    state: "stopped"
    
# -- MAC: Mandatory Access Control
selinux_all_purge: true
selinux_policy: targeted
selinux_state: permissive

# -- Storage Properties for OpenStack Installation
storage_pools:
  -  name: cinder-volumes
     disks: 
      - sda
      - sdb

# -- PackStack Properties: Single Node OpenStack Installation
packstack_default_host_ip: "192.168.1.100"
